common/models/User.php
<?php
namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 */
class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 10;


    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED]],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return bool
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }
}

backend/controllers/UserController.php
<?php

namespace backend\controllers;

use core\entities\User;
use core\forms\backend\UserRoleForm;
use core\forms\common\UserForm;
use core\forms\common\UserUpdateForm;
use core\forms\search\UserSearch;
use core\services\common\UserService;
use yii\base\Module;
use yii\db\Query;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use Yii;

class UserController extends DefaultController
{

    private $service;

    public function __construct($id, Module $module, array $config = [], UserService $service)
    {
        parent::__construct($id, $module, $config);
        $this->service = $service;
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionCreate()
    {
        $form = new UserForm();

        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            try {
                $user = $this->service->create($form);
                return $this->redirect(['profile/create', 'id' => $user->id]);
            } catch (\DomainException $e) {
                Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }

        return $this->render('create', [
            'model' => $form,
        ]);
    }

    public function actionUpdate($id)
    {
        $user = $this->findModel($id);
        $profile = $user->profile;
        $form = new UserUpdateForm($user);
        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            try {
                $this->service->edit($form, $user->id);
                return $this->redirect(['profile/update', 'id' => $profile->id]);
            } catch (\DomainException $e) {
                Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }

        return $this->render('create', [
            'model' => $form,
        ]);
    }

    public function actionView($id)
    {
        try {
            $user = $this->service->view($id);
            return $this->render('view', [
                'user' => $user
            ]);
        } catch (\DomainException $e) {
            Yii::$app->session->setFlash('error', $e->getMessage());
        }
    }

    public function actionDelete($id)
    {
        try {
            $user = $this->service->remove($id);
            Yii::$app->session->setFlash('success', Yii::t('controllers.flash', 'User was successfully deleted'));
        } catch (\DomainException $e) {
            Yii::$app->session->setFlash('error', $e->getMessage());
        }
        return $this->redirect(['index']);
    }

    public function actionActivate($id)
    {
        try {
            $user = $this->service->activate($id);
            Yii::$app->session->setFlash('success', Yii::t('controllers.flash', 'User was successfully updated'));
            return $this->redirect('index');
        } catch (\DomainException $e) {
            Yii::$app->session->setFlash('error', $e->getMessage());
            return $this->redirect('index');
        }
    }

    public function actionModerate($id)
    {
        try {
            $user = $this->service->moderate($id);
            Yii::$app->session->setFlash('success', Yii::t('controllers.flash', 'User was successfully send to moderation'));
            return $this->redirect('index');
        } catch (\DomainException $e) {
            Yii::$app->session->setFlash('error', $e->getMessage());
            return $this->redirect('index');
        }
    }

    public function actionList($q = null, $id = null)
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;
        $out = ['results' => ['id' => '', 'text' => '']];
        if (!is_null($q)) {
            $query = new Query();
            $query->select('id, email AS text')
                ->from('user')
                ->where(['like', 'email', $q])
                ->limit(20);
            $command = $query->createCommand();
            $data = $command->queryAll();
            $out['results'] = array_values($data);
        }
        elseif ($id > 0) {
            $out['results'] = ['id' => $id, 'text' => User::findOne($id)->email];
        }
        return $out;
    }

    public function actionAssignRole($id)
    {
        $form = new UserRoleForm();
        $form->user_id = $id;
        if ($form->load(Yii::$app->request->post()) && $form->validate()){
            try{
                $this->service->assignRole($form);
                return $this->redirect('index');
            }catch (\DomainException $e){
                Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }
        return $this->render('assign-role', ['model' => $form]);
    }

    public function actionGetUsers($q = null)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $out = [];
        if (!is_null($q)) {
            $query = new Query();
            $query->select('id, email AS text')
                ->from('users')
                ->where(['status' => User::STATUS_ACTIVE]);
            if (is_numeric($q)) {
                $query->andWhere(['id' => filter_var($q, FILTER_VALIDATE_INT)]);
                $query->orWhere(['like', 'email', $q]);
            } else {
                $query->andWhere(['like', 'email', $q]);
            }
            $query->orderBy(['id' => SORT_DESC])->limit(20);
            $command = $query->createCommand();
            $data = $command->queryAll();
            $out['results'] = $data;
        }
        return $out;
    }

    private function findModel($id)
    {
        if (($user = User::findOne($id)) !== null) {
            return $user;
        }
        throw new NotFoundHttpException(Yii::t('controllers.errors', 'User not found'));
    }
}

backend/views/user/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use core\helpers\CommonHelper;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $model \core\forms\common\UserForm */

?>

<div class="col-md-6">
    <div class="box box-primary">
        <?php $form = ActiveForm::begin(); ?>
        <div class="box-body">
            <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

            <?= $form->field($model, 'password')->passwordInput() ?>

            <?= $form->field($model, 'timeZone')->widget(Select2::class, [
                'data' => CommonHelper::getTimeZones(),
                'options' => [
                    'placeholder' => 'Select time zone...'
                ],
                'size' => 'lg',
                'pluginOptions' => [
                    'allowClear' => true
                ],
            ]) ?>
        </div>
        <div class="box-footer">
            <div class="form-group">
                <?= Html::submitButton(Yii::t('app', 'Save and next step'), ['class' => 'btn btn-success btn-own btn-yellow']) ?>
            </div>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>

backend/views/user/assign-role.php
<?php

use \yii\widgets\ActiveForm;
use \core\helpers\UserHelper;
use \yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model \core\forms\backend\UserRoleForm */

$this->title = Yii::t('app', 'Assign Role');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="user-role white-box">
    <?php $form = ActiveForm::begin();?>

    <?= $form->field($model, 'role_id')->dropDownList(UserHelper::roleList(), [
            'options' => [UserHelper::getRoleId($model->user_id) => ['Selected'=>'selected']],
            'prompt' => Yii::t('app', 'Select role...')
    ])?>

    <?= Html::submitButton(Yii::t('app', 'Save'));?>

    <?php ActiveForm::end()?>
</div>

backend/views/user/create.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use core\helpers\CommonHelper;


/* @var $this yii\web\View */
/* @var $model \core\forms\common\UserForm */

$this->title = Yii::t('app', 'Create User');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create white-box">
    <div class="row">
        <!-- <h1><?= Html::encode($this->title) ?></h1> -->
        <?php

        echo $this->render('_form', [
            'model' => $model
        ]);

        ?>
    </div>
</div>

backend/views/user/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use core\helpers\UserStatusHelper;

/* @var $this yii\web\View */
/* @var $searchModel core\forms\search\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Users');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="admin-index white-box">

    <!-- <h1><?= Html::encode($this->title) ?></h1> -->
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Create User'), ['create'], ['class' => 'btn btn-success btn-own btn-yellow pull-left']) ?>
    </p>
    <div class="clearfix"></div>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'email:email',
            [
                'attribute' => 'status',
                'value' => function ($model) {
                    /**
                     * @var \core\entities\User $model
                     */
                    return UserStatusHelper::getStatusLabel($model->status);
                }
            ],
            'time_zone',
            'ctime',

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update} {delete} {activate} {moderate} {role}',
                'buttons' =>
                    [
                        'delete' => function ($url, $model) {
                            /**
                             * @var \core\entities\User $model
                             */
                            return $model->isCanBeDeleted() ? Html::a('<span class="glyphicon glyphicon-trash"></span>', \yii\helpers\Url::to(['/user/delete', 'id' => $model->id]), [
                                'title' => Yii::t('yii', 'Delete user')
                            ]) : null;
                        },
                        'activate' => function ($url, $model) {
                            /**
                             * @var \core\entities\User $model
                             */
                            return $model->isCanBeActivated() ? Html::a('<span class="fa fa-thumbs-up"></span>', \yii\helpers\Url::to(['/user/activate', 'id' => $model->id]), [
                                'title' => Yii::t('yii', 'Activate user')
                            ]) : null;
                        },
                        'moderate' => function ($url, $model) {
                            /**
                             * @var \core\entities\User $model
                             */
                            return $model->isCanBeModerated() ? Html::a('<span class="fa fa-thumbs-down"></span>', \yii\helpers\Url::to(['/user/moderate', 'id' => $model->id]), [
                                'title' => Yii::t('yii', 'Send to moderate user')
                            ]) : null;
                        },
                        'role' => function ($url, $model){
                            return Html::a('<span class="fa fa-user-secret"></span>', \yii\helpers\Url::to(['user/assign-role', 'id' => $model->id]), [
                                'title' => Yii::t('yii', 'Assign role')
                            ]);
                        },
                    ]
            ],
        ],
    ]); ?>
</div>

backend/views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model \core\forms\common\UserForm */
/* @var $user \core\entities\User */

$this->title = Yii::t('app', 'Update User: {nameAttribute}', [
    'nameAttribute' => $user->email,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $user->id, 'url' => ['view', 'id' => $user->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="user-update white-box">

    <!-- <h1><?= Html::encode($this->title) ?></h1> -->

    <?php
        echo $this->render('_form', [
            'model' => $model
        ]);
    ?>

</div>

backend/views/user/view.php
<?php