backend/controllers/ProfileController.php
<?php

namespace backend\controllers;


use core\entities\Profile;
use core\exceptions\NotFoundException;
use core\forms\backend\ProfileCreateForm;
use core\forms\backend\ProfileUpdateForm;
use core\forms\search\ProfileSearch;
use core\helpers\DumpHelper;
use core\services\common\ProfileService;
use yii\base\Module;
use yii\helpers\FileHelper;
use yii\helpers\VarDumper;
use yii\web\Controller;
use Yii;
use core\entities\User;
use \core\helpers\UploadedFile;


class ProfileController extends Controller
{

    private $service;
    private $path;

    public function __construct($id, Module $module, array $config = [], ProfileService $service)
    {
        parent::__construct($id, $module, $config);
        $this->service = $service;
        $this->path = \Yii::getAlias('@api');
    }

    public function actionIndex()
    {
        $searchModel = new ProfileSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);

    }

    public function actionCreate()
    {
        $userId = Yii::$app->request->get('id');
        $form = new ProfileCreateForm();

        if (!empty($userId)){
            $form->user_id = $userId;
        }
        if ($form->load(Yii::$app->request->post())){
            $form->avatar = UploadedFile::uploaded($form, 'avatar');
            if ($form->validate()){
                try{
                    $this->service->create($form, $this->path);
                    return $this->redirect('index');
                }catch (\DomainException $e){
                    Yii::$app->session->setFlash('error', $e->getMessage());
                }
            }
        }
        return $this->render('create', ['model' => $form]);
    }

    public function actionUpdate($id)
    {
        $profile = $this->findModel($id);
        $form = new ProfileUpdateForm($profile);
        if ($form->load(Yii::$app->request->post())) {
            $form->avatar = UploadedFile::uploaded($form, 'avatar');
            if($form->validate()){
                try{
                    $this->service->edit($profile->id, $form, $this->path);
                    $this->redirect('index');
                }catch (\DomainException $e){
                    Yii::$app->session->setFlash($e->getMessage());
                }
            }

        }
        return $this->render('update', ['model' => $form, 'profile'=>$profile]);
    }

    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionDelete($id)
    {
        try{
            $this->service->delete($id);
            Yii::$app->session->setFlash('success', 'was removed');
        }catch (\DomainException $e) {
            Yii::$app->session->setFlash($e->getMessage());
        }
        return $this->redirect('index');
    }

    public function actionRemoveImage($id)
    {
        $this->service->removeImage($id, $this->path);
        return json_decode(true);
    }

    public function actionSearchUsers($q = null)
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $out = ['results' => ['id' => '', 'text' => '']];
        if (!is_null($q)) {
            $query = User::find();
            $query->select(['id' =>'id','text' => 'email'])
                ->where(['like', 'email', $q]);
            $data = $query->asArray()->all();
            $out['results'] = $data;
        }
        return $out;
    }

    private function findModel($id)
    {
        if (($model = Profile::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundException('The requested page does not exist.');
    }

}

backend/controllers/RoleController.php
<?php

namespace backend\controllers;

use core\entities\Role;
use core\forms\backend\RoleForm;
use core\helpers\DumpHelper;
use core\services\back\RoleService;
use yii\base\Module;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;

class RoleController extends DefaultController
{
    private $service;

    public function __construct($id, Module $module, array $config = [], RoleService $service)
    {
        parent::__construct($id, $module, $config);
        $this->service = $service;
    }

    public function actionIndex()
    {
        return $this->render('index', [
            'dataProvider' => new ActiveDataProvider(['query' => Role::find()])
        ]);
    }

    public function actionCreate()
    {
        $form = new RoleForm();

        if ($form->load(\Yii::$app->request->post()) && $form->validate()) {
            try {
                $role = $this->service->create($form);
                return $this->redirect('index');
            } catch (\DomainException $e) {
                \Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }

        return $this->render('create', [
            'model' => $form
        ]);
    }

    public function actionUpdate($id)
    {
        $role = $this->findRoleModel($id);
        $form = new RoleForm($role);
        if ($form->load(\Yii::$app->request->post()) && $form->validate()) {
            try {
                $role = $this->service->edit($form, $role->id);
                return $this->redirect('index');
            } catch (\DomainException $e) {
                \Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }

        return $this->render('update', [
            'model' => $form
        ]);
    }

    private function findRoleModel($id)
    {
        if (($role = Role::findOne($id)) !== null) {
            return $role;
        }
        throw new NotFoundHttpException('Page not found');
    }
}

backend/controllers/TagController.php
<?php

namespace backend\controllers;

use Yii;
use core\forms\backend\TagForm;
use core\services\back\TagService;
use core\entities\Tag;
use core\forms\search\TagSearch;
use yii\base\Module;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\db\Query;

/**
 * TagController implements the CRUD actions for Tag model.
 */
class TagController extends Controller
{
    private $service;

    public function __construct($id, Module $module, array $config = [], TagService $service)
    {
        parent::__construct($id, $module, $config);
        $this->service = $service;
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                    'change-status' => ['POST'],
                ],
            ],
        ];
    }
    /**
     * Lists all Tag models.
     * @return mixed
     */
    public function actionIndex()
    {

        $searchModel = new TagSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Tag model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $form = new TagForm();
        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            try {
                $entity = $this->service->create($form);
                \Yii::$app->session->setFlash('success', Yii::t('app', 'Tag was created!'));
                return $this->redirect('index');
            } catch (\DomainException $e) {
                \Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }

        return $this->render('create', [
            'model' => $form,
        ]);
    }

    /**
     * Updates an existing Tag model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $entity = $this->findModel($id);
        $form = new TagForm($entity);

        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            try {
            Yii::$app->session->setFlash('success', Yii::t('app', 'Tag was updated!'));
            $entity = $this->service->edit($form, $entity->id);
            return $this->redirect(['index']);
            } catch (\DomainException $e) {
                \Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }

        return $this->render('update', [
            'model' => $form,
        ]);
    }

    /**
     * Deletes an existing Tag model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        if($model->delete()){
            Yii::$app->session->setFlash('success', Yii::t('app', 'Tag was deleted!'));
        }
        else{
            Yii::$app->session->setFlash('error', Yii::t('app', 'Tag was not deleted!'));
        }
        return $this->redirect(['index']);
    }

    public function actionChangeStatus(){
        try{
            $this->service->changeStatus(Yii::$app->request->post('id'), Yii::$app->request->post('status'));
            Yii::$app->session->setFlash('success', Yii::t('app', 'Tag status was changed!'));
            return $this->redirect(Yii::$app->getRequest()->getReferrer());
        }
        catch (\DomainException $e){
            Yii::$app->session->setFlash('error', $e->getMessage());
            return $this->redirect(Yii::$app->getRequest()->getReferrer());
        }
    }

    public function actionGetTags($q = null)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $out = [];
        if (!is_null($q)) {
            $query = new Query();
            $query->select('id, name AS text')->from('tags')->where(['status' => Tag::ACTIVE]);
            if (is_numeric($q)) {
                $query->andWhere(['id' => filter_var($q, FILTER_VALIDATE_INT)]);
                $query->orWhere(['like', 'name', $q]);
            } else {
                $query->andWhere(['like', 'name', $q]);
            }
            $query->orderBy(['id' => SORT_DESC])->limit(20);
            $command = $query->createCommand();
            $data = $command->queryAll();
            $out['results'] = $data;
        }
        return $out;
    }

    /**
     * Finds the Tag model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Tag the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Tag::findOne($id)) !== null) {
            return $model;
        }
        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

backend/controllers/TaskController.php
<?php

namespace backend\controllers;

use core\forms\backend\compositeForm\TaskCreateForm;
use core\forms\backend\compositeForm\TaskUpdateForm;
use Yii;
use core\forms\backend\TaskForm;
use core\services\back\TaskService;
use core\entities\Task;
use core\forms\search\TaskSearch;
use yii\base\Module;
use yii\helpers\BaseVarDumper;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use core\helpers\UploadedFile;
use yii\db\Query;
use yii\web\Response;

class TaskController extends Controller
{
    private $service;
    private $path;

    public function __construct($id, Module $module, array $config = [], TaskService $service)
    {
        parent::__construct($id, $module, $config);
        $this->service = $service;
        $this->path = \Yii::getAlias('@api');
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                    'change-status' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Task models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TaskSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Task model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $form = new TaskCreateForm(Yii::$app->request->post());

        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            try {
                $form->uploadedFile = UploadedFile::uploads($form->files, 'file');
                $entity = $this->service->create($form, $this->path);
                \Yii::$app->session->setFlash('success', Yii::t('app', 'Task was created!'));
                return $this->redirect('index');
            } catch (\DomainException $e) {
                \Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }

        return $this->render('create', [
            'model' => $form
        ]);
    }

    /**
     * Updates an existing Task model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $entity = $this->findModel($id);
        $form = new TaskUpdateForm(Yii::$app->request->post(), $entity);

        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            try {
                $form->uploadedFile = UploadedFile::uploads($form->files, 'file');
                $entity = $this->service->edit($form, $this->path, $entity->id);
                Yii::$app->session->setFlash('success', Yii::t('app', 'Task was updated!'));
                return $this->redirect(['index']);
            } catch (\DomainException $e) {
                \Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }

        return $this->render('update', [
            'model' => $form,
            'task' => $entity
        ]);
    }

    /**
     * Deletes an existing Task model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        try {
            $this->service->delete($id);
            Yii::$app->session->setFlash('success', 'Task was deleted!');
        } catch (\DomainException $e) {
            Yii::$app->session->setFlash($e->getMessage());
        }
        return $this->redirect('index');
    }

    public function actionChangeStatus()
    {
        try{
            $this->service->changeStatus(Yii::$app->request->post('id'), Yii::$app->request->post('status'));
            Yii::$app->session->setFlash('success', Yii::t('app', 'Task status was changed!'));
            return $this->redirect(Yii::$app->getRequest()->getReferrer());
        }
        catch (\DomainException $e){
            Yii::$app->session->setFlash('error', $e->getMessage());
            return $this->redirect(Yii::$app->getRequest()->getReferrer());
        }
    }

    public function actionGetRelations($q = null)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $out = [];
        if (!is_null($q)) {
            $query = new Query();
            $query->select('id, title AS text')
                ->from('tasks')
                ->where(['status' => Task::ACTIVE]);
            if (is_numeric($q)) {
                $query->andWhere(['id' => filter_var($q, FILTER_VALIDATE_INT)]);
                $query->orWhere(['like', 'title', $q]);
            } else {
                $query->andWhere(['like', 'title', $q]);
            }
            $query->orderBy(['id' => SORT_DESC])->limit(20);
            $command = $query->createCommand();
            $data = $command->queryAll();
            $out['results'] = $data;
        }
        return $out;
    }

    public function actionRemoveImage($id)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        try{
            $this->service->removeImage($id, $this->path);
            return true;
        }
        catch (\DomainException $e){
            return false;
        }
    }

    /**
     * Finds the TaskType model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Task the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Task::findOne($id)) !== null) {
            return $model;
        }
        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

backend/views/layouts/header.php
<?php
use yii\helpers\Html;
use core\helpers\LanguagesHelper;

/* @var $this \yii\web\View */
/* @var $content string */
?>

<header class="main-header">

    <?= Html::a('<span class="logo-mini">CRM</span><span class="logo-lg">' . Yii::$app->name . '</span>', Yii::$app->homeUrl, ['class' => 'logo']) ?>

    <nav class="navbar navbar-static-top" role="navigation">
    </nav>
</header>

backend/views/layouts/left.php
<?php
    use yii\widgets\ActiveForm;
    use core\forms\backend\SetLangForm;
    use core\forms\backend\SearchForm;
    use core\helpers\LanguagesHelper;
?>

<?php

$langForm = new SetLangForm(Yii::$app->user->identity->getUser());
$searchForm = new SearchForm();
?>

<aside class="main-sidebar">

    <section class="sidebar">

        <!-- Sidebar user panel -->
        <div class="user-panel" style="padding: 10px 10px 20px 10px;">
            <div class="pull-left image">
                <img src="<?= $directoryAsset ?>/img/user2-160x160.jpg" class="img-circle" alt="User Image"/>
            </div>
            <div class="pull-left info">
                <p>Alexander Pierce</p>

                <?= \yii\helpers\Html::a(
                    'Sign out',
                    ['/logout'],
                    ['data-method' => 'post', 'class' => 'btn btn-info']
                ) ?>
            </div>
        </div>

        <?php

        $form = ActiveForm::begin([
            'action' => ['/search/search'],
            'method' => 'get',
            'options' => [
                'class' => 'sidebar-form search-form white-form'
            ],
            'fieldConfig' => [
                'options' => ['class' => 'input-group'],
            ],
        ]);

        echo $form->field($searchForm, 'q', [
            'template' =>
                '{input}<span class="input-group-btn"><button type="submit"class="btn btn-flat btn-search"><i class="fa fa-search"></i></button>'
        ])->textInput(['class' => 'form-control form-control-own', 'placeholder' => 'Search...']);

        ActiveForm::end();
        ?>

        <?php

        $form = ActiveForm::begin([
            'action' => ['/admin/set-lang'],
            'method' => 'post',
            'options' => [
                'class' => 'sidebar-form search-form white-form'
            ],
            'fieldConfig' => [
                'options' => ['class' => 'input-group'],
            ],
        ]);

        echo $form->field($langForm, 'lang', ['template' => '{input}'])->dropDownList(LanguagesHelper::getList())->label(false);

        ActiveForm::end();
        ?>
        <!-- /.search form -->

        <?= dmstr\widgets\Menu::widget(
            [
                'options' => ['class' => 'sidebar-menu sidebar-menu-own tree', 'data-widget' => 'tree'],
                'items' => [
                    ['label' => 'Menu', 'options' => ['class' => 'header']],
                    [
                        'label' => Yii::t('layout.menu','Admins'),
                        'icon' => 'user',
                        'visible' => Yii::$app->user->can('admin'),
                        'url' => '#',
                        'items' => [
                            ['label' => Yii::t('layout.menu','Roles'), 'icon' => 'users', 'url' => ['/access/role'],],
                            ['label' => Yii::t('layout.menu','Permissions'), 'icon' => 'unlock-alt', 'url' => ['/access/permission'],],
                            ['label' => Yii::t('layout.menu','Add admin'), 'icon' => 'user-plus', 'url' => ['/admin/create'],],
                            ['label' => Yii::t('layout.menu','Admins list'), 'icon' => 'list-ol', 'url' => ['/admin/index'],],
                        ],
                    ],
                    [
                        'visible' => Yii::$app->user->can('user'),
                        'label' => Yii::t('layout.menu','Users'),
                        'icon' => 'users',
                        'url' => '#',
                        'items' => [
                            ['label' => Yii::t('layout.menu','Add user'), 'icon' => 'user-plus', 'url' => ['/user/create'],],
                            ['label' => Yii::t('layout.menu','Users list'), 'icon' => 'list-ol', 'url' => ['/user/index'],],
                        ],
                    ],

                    [
                        'visible' => Yii::$app->user->can('profile'),
                        'label' => Yii::t('layout.menu','Profiles'),
                        'icon' => 'users',
                        'url' => '#',
                        'items' => [
                            ['label' => Yii::t('layout.menu','Add profile'), 'icon' => 'user-plus', 'url' => ['/profile/create'],],
                            ['label' => Yii::t('layout.menu','Profiles list'), 'icon' => 'list-ol', 'url' => ['/profile/index'],],
                        ],
                    ],
                    [
                        'visible' => Yii::$app->user->can('position'),
                        'label' => Yii::t('layout.menu','Position'),
                        'icon' => 'sitemap',
                        'url' => '#',
                        'items' => [
                            ['label' => Yii::t('layout.menu','Add position'), 'icon' => 'plus', 'url' => ['/position/create'],],
                            ['label' => Yii::t('layout.menu','Position list'), 'icon' => 'list-ol', 'url' => ['/position/index'],],
                        ],
                    ],
                    [
                        'label' => Yii::t('layout.menu','Front Roles'),
                        'icon' => 'user',
                        'visible' => Yii::$app->user->can('role'),
                        'url' => '#',
                        'items' => [
                            ['label' => Yii::t('layout.menu','Add role'), 'icon' => 'user-plus', 'url' => ['/role/create'],],
                            ['label' => Yii::t('layout.menu','Roles list'), 'icon' => 'list-ol', 'url' => ['/role/index'],],
                        ],
                    ],
                    [
                        'visible' => Yii::$app->user->can('language'),
                        'label' => Yii::t('layout.menu','Languages'),
                        'icon' => 'language',
                        'url' => '#',
                        'items' => [
                            ['label' => Yii::t('layout.menu','Add language'), 'icon' => 'plus', 'url' => ['/language/create'],],
                            ['label' => Yii::t('layout.menu','Languages list'), 'icon' => 'list-ol', 'url' => ['/language/index'],],
                        ],
                    ],
                    [
                        'visible' => Yii::$app->user->can('translate'),
                        'label' => Yii::t('layout.menu','Translations'),
                        'icon' => 'cogs',
                        'url' => ['/translate/index'],
                    ],
                    [
                        'visible' => Yii::$app->user->can('version'),
                        'label' => Yii::t('layout.menu','Version'),
                        'icon' => 'refresh',
                        'url' => ['/version/index'],
                    ],
                    [
                        'visible' => Yii::$app->user->can('project'),
                        'label' => Yii::t('layout.menu','Project'),
                        'icon' => 'th',
                        'url' => ['/project/index'],
                    ],
                    [
                        'visible' => Yii::$app->user->can('tag'),
                        'label' => Yii::t('layout.menu','Tags'),
                        'icon' => 'tags',
                        'url' => ['/tag/index'],
                    ],
                    [
                        'visible' => Yii::$app->user->can('options'),
                        'label' => Yii::t('layout.menu','Options'),
                        'icon' => 'ellipsis-v',
                        'url' => ['/options/index'],
                    ],
                    [
                        'visible' => Yii::$app->user->can('task'),
                        'label' => Yii::t('layout.menu','Tasks'),
                        'icon' => 'tasks',
                        'url' => ['/task/index'],
                    ],
                    [
                        //'visible' => Yii::$app->user->can('taskType'),
                        'label' => Yii::t('layout.menu','Tasks Type'),
                        'icon' => 'share-alt',
                        'url' => ['/task-type/index'],
                    ],
                    [
                        //'visible' => Yii::$app->user->can('taskType'),
                        'label' => Yii::t('layout.menu','Wiki'),
                        'icon' => 'share-alt',
                        'url' => ['wiki/content/index'],
                    ]
                ],

            ]
        ) ?>
    </section>
</aside>

backend/views/layouts/main-login.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

dmstr\web\AdminLteAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login-page">

<?php $this->beginBody() ?>

    <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/main.php
<?php
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

backend\assets\AppAsset::register($this);

dmstr\web\AdminLteAsset::register($this);

$directoryAsset = Yii::$app->assetManager->getPublishedUrl('@vendor/almasaeed2010/adminlte/dist');

if (!Yii::$app->user->isGuest){
    $this->registerJs("setTimeZone('".Yii::$app->user->identity->getTimezone()."');");
}
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js" crossorigin="anonymous"></script>
    <?php $this->head() ?>
</head>
<body class="hold-transition skin-blue sidebar-mini">
<?php $this->beginBody() ?>
<div class="wrapper">

    <?= $this->render(
        'header.php',
        ['directoryAsset' => $directoryAsset]
    ) ?>

    <?= $this->render(
        'left.php',
        ['directoryAsset' => $directoryAsset]
    )
    ?>

    <?= $this->render(
        'content.php',
        ['content' => $content, 'directoryAsset' => $directoryAsset]
    ) ?>

</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>