backend/controllers/LanguageController.php
<?php

namespace backend\controllers;

use core\entities\Language;
use core\forms\backend\LanguageForm;
use core\forms\search\LanguageSearch;
use core\services\back\LanguageService;
use yii\base\Module;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use Yii;

class LanguageController extends DefaultController
{
    private $service;

    public function __construct($id, Module $module, array $config = [], LanguageService $service)
    {
        parent::__construct($id, $module, $config);
        $this->service = $service;
    }

    public function actionCreate()
    {
        $form = new LanguageForm();

        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            try {
                $lang = $this->service->create($form);
                return $this->redirect(['index']);
            } catch (\DomainException $e) {
                Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }

        return $this->render('create', [
            'model' => $form
        ]);
    }

    public function actionUpdate($id)
    {
        $lang = $this->findModel($id);

        $form = new LanguageForm($lang);

        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            try {
                $lang = $this->service->edit($form, $lang->id);
                return $this->redirect(['index']);
            } catch (\DomainException $e) {
                Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }

        return $this->render('update', [
            'model' => $form
        ]);
    }

    public function actionIndex()
    {
        $searchModel = new LanguageSearch();
        $dataProvider = $searchModel->search(\Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionDelete($id)
    {
        try {
            $lang = $this->service->remove($id);
            Yii::$app->session->setFlash('success', Yii::t('controllers.flash', 'Language was successfully deleted'));
        } catch (\DomainException $e) {
            Yii::$app->session->setFlash('error', $e->getMessage());
        }
        return $this->redirect(['index']);
    }

    public function actionRestore($id)
    {
        try {
            $lang = $this->service->restore($id);
            Yii::$app->session->setFlash('success', Yii::t('controllers.flash', 'Language was successfully restored'));
            return $this->redirect('index');
        } catch (\DomainException $e) {
            Yii::$app->session->setFlash('error', $e->getMessage());
            return $this->redirect('index');
        }
    }

    protected function findModel($id)
    {
        if (($lang = Language::findOne($id)) !== null) {
            return $lang;
        }
        throw new NotFoundHttpException(Yii::t('controllers.errors', 'Language not found'));
    }
}

backend/views/language/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $model \core\forms\backend\LanguageForm */

?>

<div class="col-md-6">
    <div class="box box-primary">
        <?php $form = ActiveForm::begin(); ?>
        <div class="box-body">
            <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

            <?= $form->field($model, 'iso')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="box-footer">
            <div class="form-group">
                <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success btn-own btn-yellow']) ?>
            </div>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>

backend/views/language/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model \core\forms\backend\LanguageForm */

$this->title = Yii::t('app', 'Create Language');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Languages'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create white-box">
    <div class="row">
        <!-- <h1><?= Html::encode($this->title) ?></h1> -->
        <?php

        echo $this->render('_form', [
            'model' => $model
        ]);

        ?>
    </div>
</div>

backend/views/language/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use core\helpers\LanguagesHelper;

/* @var $this yii\web\View */
/* @var $searchModel \core\forms\search\LanguageSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Languages';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="currency-index white-box">

    <!-- <h1><?= Html::encode($this->title) ?></h1> -->
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Language', ['create'], ['class' => 'btn btn-success btn-own btn-yellow pull-left']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'title',
            'iso',
            [
                'attribute' => 'status',
                'value' => function ($model) {
                    /**
                     * @var \core\entities\Language $model
                     */
                    return LanguagesHelper::getStatusLabel($model->status);
                }
            ],
            'ctime',

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update} {delete} {restore}',
                'buttons' =>
                    [
                        'delete' => function ($url, $model) {
                            /**
                             * @var \core\entities\Language $model
                             */
                            return $model->isActive() ? Html::a('<span class="glyphicon glyphicon-trash"></span>', \yii\helpers\Url::to(['/language/delete', 'id' => $model->id]), [
                                'title' => Yii::t('yii', 'Delete language')
                            ]) : null;
                        },
                        'restore' => function ($url, $model) {
                            /**
                             * @var \core\entities\Language $model
                             */
                            return $model->isDeleted() ? Html::a('<span class="fa fa-retweet"></span>', \yii\helpers\Url::to(['/language/restore', 'id' => $model->id]), [
                                'title' => Yii::t('yii', 'Restore language')
                            ]) : null;
                        }
                    ]
            ],
        ],
    ]); ?>
</div>

backend/views/language/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model \core\forms\backend\LanguageForm */
/* @var $lang \core\entities\Language */

$this->title = Yii::t('app', 'Update Language: {nameAttribute}', [
    'nameAttribute' => $lang->iso,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Languages'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $lang->id, 'url' => ['view', 'id' => $lang->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="user-update white-box">

    <!-- <h1><?= Html::encode($this->title) ?></h1> -->

    <?php
    echo $this->render('_form', [
        'model' => $model
    ]);
    ?>

</div>